const users = [
        {
        "id": 1,
        "firstName": "Roselle",
        "lastName": "Antoniazzi",
        "email": "rantoniazzi0@comcast.net",
        "username": "rantoniazzi0",
        "devType": "VP Accounting",
        "availble": false,
        "bio": "ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis",
        "skills": "Javascript, Typescript, CSS, HTML, React, Bootstrap,Ruby, Rust, SQL",
        "rating": 1
    },
    {
        "id": 2,
        "firstName": "Claybourne",
        "lastName": "Snufflebottom",
        "email": "csnufflebottom1@desdev.cn",
        "username": "csnufflebottom1",
        "devType": "Sales Representative",
        "availble": true,
        "bio": "dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut",
        "skills": "AI, ML, Architecture, DevOps, PHP, Ruby, Rust, SQL, NoSQL, Python, Golang",
        "rating": 3
    },
    {
        "id": 3,
        "firstName": "Luelle",
        "lastName": "Bolingbroke",
        "email": "lbolingbroke2@bizjournals.com",
        "username": "lbolingbroke2",
        "devType": "Pharmacist",
        "availble": true,
        "bio": "orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu",
        "skills": "Python, Golang",
        "rating": 3
    },
    {
        "id": 4,
        "firstName": "Oliver",
        "lastName": "Postins",
        "email": "opostins3@state.gov",
        "username": "opostins3",
        "devType": "Account Executive",
        "availble": true,
        "bio": "vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit",
        "skills": "Architecture, DevOps, SQL, NoSQL, Python",
        "rating": 1
    },
    {
        "id": 5,
        "firstName": "Kizzie",
        "lastName": "Jordine",
        "email": "kjordine4@wikia.com",
        "username": "kjordine4",
        "devType": "Nuclear Power Engineer",
        "availble": false,
        "bio": "nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit",
        "skills": "Javascript, Typescript, CSS, HTML, React",
        "rating": 1
    },
    {
        "id": 6,
        "firstName": "Odele",
        "lastName": "Heyfield",
        "email": "oheyfield5@shutterfly.com",
        "username": "oheyfield5",
        "devType": "Sales Representative",
        "availble": true,
        "bio": "molestie lorem quisque ut erat curabitur gravida nisi at nibh in",
        "skills": "NoSQL, Python, Golang",
        "rating": 3
    },
    {
        "id": 7,
        "firstName": "Sofie",
        "lastName": "Gaunson",
        "email": "sgaunson6@blogspot.com",
        "username": "sgaunson6",
        "devType": "Staff Scientist",
        "availble": false,
        "bio": "nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum",
        "skills": "Javascript, Crypto, AI, ML, Python, Golang",
        "rating": 1
    },
    {
        "id": 8,
        "firstName": "Dulcie",
        "lastName": "Praten",
        "email": "dpraten7@google.es",
        "username": "dpraten7",
        "devType": "Financial Advisor",
        "availble": true,
        "bio": "vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in",
        "skills": "Javascript, Python, Golang",
        "rating": 5
    },
    {
        "id": 9,
        "firstName": "Hi",
        "lastName": "Minguet",
        "email": "hminguet8@sakura.ne.jp",
        "username": "hminguet8",
        "devType": "Administrative Assistant I",
        "availble": false,
        "bio": "varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar",
        "skills": "Javascript, CSS, HTML, React, Bootstrap",
        "rating": 2
    },
    {
        "id": 10,
        "firstName": "Kasey",
        "lastName": "Ourtic",
        "email": "kourtic9@geocities.jp",
        "username": "kourtic9",
        "devType": "Associate Professor",
        "availble": false,
        "bio": "orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae",
        "skills": "Javascript, Typescript, Rust, SQL, NoSQL",
        "rating": 4
    },
    {
        "id": 11,
        "firstName": "Haily",
        "lastName": "Cron",
        "email": "hcrona@elegantthemes.com",
        "username": "hcrona",
        "devType": "Compensation Analyst",
        "availble": true,
        "bio": "nam nulla integer pede justo lacinia eget tincidunt eget tempus",
        "skills": "Typescript",
        "rating": 4
    },
    {
        "id": 12,
        "firstName": "Sheffield",
        "lastName": "Smerdon",
        "email": "ssmerdonb@imageshack.us",
        "username": "ssmerdonb",
        "devType": "Editor",
        "availble": true,
        "bio": "vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque",
        "skills": "SQL, NoSQL, Python, Golang",
        "rating": 3
    },
    {
        "id": 13,
        "firstName": "Ezra",
        "lastName": "Kieran",
        "email": "ekieranc@bigcartel.com",
        "username": "ekieranc",
        "devType": "Marketing Assistant",
        "availble": false,
        "bio": "interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus",
        "skills": "Rust",
        "rating": 3
    },
    {
        "id": 14,
        "firstName": "Osgood",
        "lastName": "Escudier",
        "email": "oescudierd@europa.eu",
        "username": "oescudierd",
        "devType": "Chemical Engineer",
        "availble": true,
        "bio": "aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel",
        "skills": "Javascript, Crypto, Ruby, Rust, SQL, NoSQL",
        "rating": 1
    },
    {
        "id": 15,
        "firstName": "Audrey",
        "lastName": "Liggett",
        "email": "aliggette@paypal.com",
        "username": "aliggette",
        "devType": "Human Resources Assistant I",
        "availble": false,
        "bio": "ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla",
        "skills": "Javascript, Typescript, CSS, HTML, React, Python, Golang",
        "rating": 4
    },
    {
        "id": 16,
        "firstName": "Adele",
        "lastName": "Sotworth",
        "email": "asotworthf@barnesandnoble.com",
        "username": "asotworthf",
        "devType": "Payment Adjustment Coordinator",
        "availble": false,
        "bio": "dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus",
        "skills": "Javascript, CSS, HTML, React, NoSQL, Python",
        "rating": 4
    }
]